<#
    PixelMania - one-command build + commit + deploy for the Landfill seasonal race event.

    WHY THIS EXISTS
    ---------------
    The Landfill work spans two repos and, critically, a set of GENERATED build artifacts that
    are committed to git (server.js, server_landfill_event.js, postgres_store.js, ...). The
    server does not run src/*.ts -- it runs those generated .js files. A source edit that is not
    followed by `npm run build:*` produces a commit that looks complete, deploys cleanly, and
    changes nothing at runtime.

    That exact failure already happened once on this feature: a fix to
    src/server_landfill_event.ts was written 15 minutes AFTER the last build, so the deployed
    server_landfill_event.js still contained the pre-fix code. It presented as the client hanging
    at 88% on every Join Race, and cost a long debugging session to find -- the source on disk was
    correct the whole time, which is precisely what made it so hard to see.

    So this script does not just chain commands. After building, it re-reads the generated
    artifacts and asserts the new code is actually in them (STEP 3). If the sync step silently
    did not run, it fails HERE, loudly, instead of shipping a stale build.

    WHAT IT DOES
    ------------
      1. Sanity-checks both repo paths.
      2. Confirms the Landfill source markers are present (did the edits actually land?).
      3. npm run check:typescript   -- rebuilds every generated artifact and runs the full gate
                                       chain, including scripts/check_server_landfill_event_build.js
      4. Verifies the generated .js really contains the new code (the stale-artifact guard).
      5. Commits ONLY the named Landfill files in each repo.
      6. Runs .\deploy_staging.ps1

    SAFETY
    ------
      * Never runs promote_staging_to_production.ps1. Staging only, by construction.
      * Only ever `git add`s an explicit list of files. It will never sweep in unrelated
        work-in-progress (notably the IAP/Stripe changes, which must stay uncommitted).
      * Skips the commit step cleanly when a repo has nothing staged, so re-running after a
        partial failure is safe.

    USAGE
        cd G:\PixelMania\PixelManiaServer
        .\build_commit_deploy_landfill.ps1                 # build, commit both repos, deploy
        .\build_commit_deploy_landfill.ps1 -SkipDeploy     # build + commit only
        .\build_commit_deploy_landfill.ps1 -DryRun         # show what would happen, change nothing
        .\build_commit_deploy_landfill.ps1 -Fast           # deploy with -Fast (skips local preflight)
#>

param(
    [string]$ClientRepo = "G:\PixelMania\pixel-mania",
    [string]$ServerMessage = "feat(landfill): authoritative race sessions, fresh world per race, Join Race door policy",
    [string]$ClientMessage = "feat(landfill): race HUD, event card, fail-fast on terminal join rejections",
    [switch]$SkipDeploy,
    [switch]$SkipClient,
    [switch]$DryRun,
    [switch]$Fast
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$ServerRepo = $PSScriptRoot

# Files this feature owns, per repo. Explicit lists on purpose -- see SAFETY above.
$ServerSources = @(
    "src/server_landfill_event.ts",
    "src/server.ts",
    "src/postgres_store.ts",
    "src/server_phase7_dispatcher.ts",
    "src/server_phase8_player_session_routes.ts",
    "ecosystem.config.js",
    "scripts/check_server_landfill_event_build.js",
    "build_commit_deploy_landfill.ps1"
)
# Generated by the build. Committed, because the server runs THESE, not the .ts sources.
$ServerArtifacts = @(
    "server_landfill_event.js",
    "server.js",
    "postgres_store.js",
    "server_phase7_dispatcher.js",
    "server_phase8_player_session_routes.js"
)
$ClientFiles = @(
    "project.godot",
    "Scripts/landfill_race_hud.gd",
    "Scripts/network_manager.gd",
    "Scripts/world.gd",
    "Scripts/world_loading_ui_manager.gd",
    "Scripts/ui/lobby_scene.gd"
)

function Write-Step($text) {
    Write-Host ""
    Write-Host "=== $text ===" -ForegroundColor Cyan
}

function Assert-Contains($path, $needle, $why) {
    if (-not (Test-Path -LiteralPath $path)) { throw "Missing expected file: $path" }
    $content = Get-Content -LiteralPath $path -Raw
    if (-not $content.Contains($needle)) {
        throw "$path is missing '$needle' -- $why"
    }
}

# -------------------------------------------------------------------------------------------
Write-Step "1/6  Checking repo paths"
if (-not (Test-Path (Join-Path $ServerRepo "package.json"))) {
    throw "Run this from the PixelManiaServer folder (package.json not found in $ServerRepo)."
}
if (-not (Test-Path (Join-Path $ServerRepo "deploy_staging.ps1"))) {
    throw "Missing deploy_staging.ps1 in $ServerRepo"
}
if (-not $SkipClient -and -not (Test-Path (Join-Path $ClientRepo "project.godot"))) {
    throw "Client repo not found at $ClientRepo (pass -ClientRepo <path>, or -SkipClient)."
}
Write-Host "  Server: $ServerRepo" -ForegroundColor DarkGray
Write-Host "  Client: $ClientRepo" -ForegroundColor DarkGray

# -------------------------------------------------------------------------------------------
Write-Step "2/6  Confirming the Landfill source edits are present"
# Cheap, high-signal markers -- one per distinct piece of the feature. If a file got reverted or
# a write-back never landed, this fails before spending minutes on a build.
Assert-Contains (Join-Path $ServerRepo "src/server_landfill_event.ts") "canonicalInstanceKey" `
    "the instance-key normalization fix is missing"
Assert-Contains (Join-Path $ServerRepo "src/server_landfill_event.ts") "admittedUsernames" `
    "the Join Race door policy is missing"
Assert-Contains (Join-Path $ServerRepo "src/server_landfill_event.ts") "waiting_for_players" `
    "the race session state machine is missing"
Assert-Contains (Join-Path $ServerRepo "src/postgres_store.ts") "landfill_race_results" `
    "the race results table is missing"
Assert-Contains (Join-Path $ServerRepo "src/server.ts") "getWorldPlayerIdentities" `
    "the session roster adapter is missing"
Assert-Contains (Join-Path $ServerRepo "ecosystem.config.js") "LANDFILL_RACE_SECONDS" `
    "the race timing config was never wired into PM2"
if (-not $SkipClient) {
    Assert-Contains (Join-Path $ClientRepo "Scripts/landfill_race_hud.gd") "landfill_race_state_received" `
        "the competitor HUD is missing"
    Assert-Contains (Join-Path $ClientRepo "Scripts/world_loading_ui_manager.gd") "join_race_required" `
        "the terminal-rejection reason is missing"
    Assert-Contains (Join-Path $ClientRepo "Scripts/ui/lobby_scene.gd") "LandfillEventCard" `
        "the lobby event card is missing"
}
Write-Host "  All source markers present." -ForegroundColor DarkGray

# -------------------------------------------------------------------------------------------
Write-Step "3/6  Building all generated artifacts + running the gate chain"
if ($DryRun) {
    Write-Host "  [DryRun] would run: npm run check:typescript" -ForegroundColor DarkYellow
} else {
    Push-Location $ServerRepo
    try {
        npm run check:typescript
        if ($LASTEXITCODE -ne 0) { throw "FAILED: npm run check:typescript" }
    } finally {
        Pop-Location
    }
    Write-Host "  Build + gates passed." -ForegroundColor DarkGray
}

# -------------------------------------------------------------------------------------------
Write-Step "4/6  Verifying the generated artifacts actually contain the new code"
# THE GUARD. This is the whole reason this script exists -- see the header. A green build above
# does not prove the sync step wrote the new code into the files the server actually runs.
if ($DryRun) {
    Write-Host "  [DryRun] skipping artifact verification (nothing was built)." -ForegroundColor DarkYellow
} else {
    Assert-Contains (Join-Path $ServerRepo "server_landfill_event.js") "canonicalInstanceKey" `
        "STALE ARTIFACT: the build did not regenerate it. Run 'npm run build:server-landfill-event' and re-check."
    Assert-Contains (Join-Path $ServerRepo "server_landfill_event.js") "admittedUsernames" `
        "STALE ARTIFACT: the door policy is not in the file the server actually runs."
    Assert-Contains (Join-Path $ServerRepo "postgres_store.js") "landfill_race_results" `
        "STALE ARTIFACT: the results table is not in the generated postgres_store.js."
    Assert-Contains (Join-Path $ServerRepo "server.js") "getWorldPlayerIdentities" `
        "STALE ARTIFACT: the roster adapter is not in the generated server.js."
    Write-Host "  Generated artifacts are in sync with source." -ForegroundColor Green
}

# -------------------------------------------------------------------------------------------
Write-Step "5/6  Committing (named files only)"

function Commit-Repo($repo, $files, $message, $label) {
    $existing = @()
    foreach ($f in $files) {
        if (Test-Path -LiteralPath (Join-Path $repo $f)) { $existing += $f }
        else { Write-Host "  skipping missing $label file: $f" -ForegroundColor DarkYellow }
    }
    if ($existing.Count -eq 0) {
        Write-Host "  Nothing to add for $label." -ForegroundColor DarkYellow
        return
    }

    if ($DryRun) {
        Write-Host "  [DryRun] would: git -C $repo add $($existing -join ' ')" -ForegroundColor DarkYellow
        Write-Host "  [DryRun] would: git -C $repo commit -m ""$message""" -ForegroundColor DarkYellow
        return
    }

    git -C $repo add -- $existing
    if ($LASTEXITCODE -ne 0) { throw "FAILED: git add in $repo" }

    # Nothing staged is a normal outcome when re-running after a partial failure, not an error.
    git -C $repo diff --cached --quiet -- $existing
    if ($LASTEXITCODE -eq 0) {
        # ${label} not $label -- PowerShell treats "$label:" as a SCOPE-qualified variable
        # reference (the same syntax as $global:x / $env:PATH), so the colon has to be pushed
        # outside the name with braces or the file fails to parse at all.
        Write-Host "  ${label}: no changes staged, skipping commit." -ForegroundColor DarkGray
        return
    }

    git -C $repo commit -m $message
    if ($LASTEXITCODE -ne 0) { throw "FAILED: git commit in $repo" }
    Write-Host "  $label committed." -ForegroundColor Green
}

Commit-Repo $ServerRepo ($ServerSources + $ServerArtifacts) $ServerMessage "server"
if (-not $SkipClient) {
    Commit-Repo $ClientRepo $ClientFiles $ClientMessage "client"
} else {
    Write-Host "  -SkipClient set, leaving the client repo alone." -ForegroundColor DarkYellow
}

# Surface anything else that is dirty, so an unrelated generated file that the build touched is
# noticed rather than silently left behind (the deploy preflight refuses in that case).
if (-not $DryRun) {
    $dirty = git -C $ServerRepo status --porcelain
    if ($dirty) {
        Write-Host ""
        Write-Host "  NOTE: other uncommitted changes remain in the server repo:" -ForegroundColor DarkYellow
        $dirty | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkYellow }
        Write-Host "  If any are GENERATED .js files, the deploy preflight will refuse until they are" -ForegroundColor DarkYellow
        Write-Host "  committed. Anything else (e.g. in-progress IAP work) is fine to leave." -ForegroundColor DarkYellow
    }
}

# -------------------------------------------------------------------------------------------
Write-Step "6/6  Deploying to STAGING"

# deploy_to_droplet.ps1's Assert-LocalPreflightPreservedBackendCommit demands the backend repo be
# COMPLETELY clean -- no tracked diff vs HEAD, and no untracked files at all:
#
#     $trackedDiff   = git diff --name-only HEAD --
#     $untrackedFiles = git ls-files --others --exclude-standard
#     if ($trackedDiff -or $untrackedFiles) { throw ... }
#
# That is a stricter bar than "the Landfill files are committed". Any stray untracked file in the
# server repo -- a scratch note, a log, this helper script before it was first committed -- blocks
# the deploy. Checking it HERE turns that into a clear, actionable message instead of an exception
# thrown from deep inside deploy_to_droplet.ps1 with a stack trace attached.
if (-not $DryRun) {
    $trackedDirty = git -C $ServerRepo diff --name-only HEAD --
    $untracked = git -C $ServerRepo ls-files --others --exclude-standard
    if ($trackedDirty -or $untracked) {
        Write-Host ""
        Write-Host "  Backend repo is not clean, so the deploy would refuse:" -ForegroundColor Red
        if ($trackedDirty) {
            Write-Host "    modified (tracked):" -ForegroundColor Red
            $trackedDirty | ForEach-Object { Write-Host "      $_" -ForegroundColor Red }
        }
        if ($untracked) {
            Write-Host "    untracked:" -ForegroundColor Red
            $untracked | ForEach-Object { Write-Host "      $_" -ForegroundColor Red }
        }
        Write-Host ""
        Write-Host "  Commit them, or add them to .gitignore if they are scratch files:" -ForegroundColor Yellow
        Write-Host "      git -C `"$ServerRepo`" add -A"
        Write-Host "      git -C `"$ServerRepo`" commit -m ""chore: commit remaining backend files before deploy"""
        Write-Host ""
        Write-Host "  Careful with 'add -A' if you have work-in-progress you do NOT want committed" -ForegroundColor Yellow
        Write-Host "  (e.g. the IAP/Stripe changes) -- add those to .gitignore or stash them instead." -ForegroundColor Yellow
        throw "Backend repo not clean; refusing to start the deploy."
    }
    Write-Host "  Backend repo is clean." -ForegroundColor DarkGray
}

if ($SkipDeploy) {
    Write-Host "  -SkipDeploy set. Deploy manually with:  .\deploy_staging.ps1" -ForegroundColor Yellow
} elseif ($DryRun) {
    Write-Host "  [DryRun] would run: .\deploy_staging.ps1" -ForegroundColor DarkYellow
} else {
    Push-Location $ServerRepo
    try {
        # Staging only. This script never calls promote_staging_to_production.ps1.
        if ($Fast) { .\deploy_staging.ps1 -Fast } else { .\deploy_staging.ps1 }
        if ($LASTEXITCODE -ne 0) { throw "FAILED: deploy_staging.ps1" }
    } finally {
        Pop-Location
    }
    Write-Host "  Deployed to staging." -ForegroundColor Green
}

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host ""
Write-Host "Verify in this order -- each step isolates a different piece:" -ForegroundColor Yellow
Write-Host "  1. Two clients press Go Green  -> panel shows 2/2, 'Starting in 10...', then the race clock"
Write-Host "  2. Break trash during the race -> KG ticks up live and the ranking reorders"
Write-Host "  3. Let the clock run out       -> results, then auto-return to the lobby after ~8s"
Write-Host "  4. Open the leaderboard        -> your total rose by exactly what the HUD showed"
Write-Host "  5. Type the instance name into the lobby JOIN field -> refused immediately"
Write-Host "  6. Press Go Green again        -> a DIFFERENT LANDFILL_xxxxxx world, different terrain"
Write-Host ""
Write-Host "If something misbehaves:" -ForegroundColor Yellow
Write-Host "    sudo -u pixelmania-stg pm2 logs --lines 100 --nostream"
Write-Host "  The [WORLD_JOIN] and [landfill] lines name the exact stage."
