<#
    PixelMania - one-command build + commit + deploy for the "item consumed but the block or
    seed never placed" fix (reported as happening during signal jitter).

    WHAT THE FIX IS
    ---------------
    server_socket_delivery_helpers.ts::sendRawJsonToSocket() silently discarded ANY packet once
    socket.bufferedAmount passed SERVER_WEBSOCKET_MAX_BUFFERED_AMOUNT -- no queue, no retry.
    Only player_position_batch had its own coalescing retry queue; the authoritative world_update
    place echo and the inventory delta shared the same drop path. The placement itself was already
    atomic, so the server had the block and had charged the item while the client was simply never
    told. Now only packet types in droppablePacketTypes may be dropped; everything else is handed
    to ws to queue in order, and past a much higher hard ceiling the socket is terminated so the
    client reconnects and resyncs from PostgreSQL.

    Also in this change: the legacy world_seed_update route now commits the seed cost atomically
    with world state, and the client tracks/reconciles placements it did not predict (locks, water,
    opt-out items) and seed plants, so a lost echo self-heals instead of persisting.

    WHY THIS SCRIPT EXISTS
    ----------------------
    src/*.ts is source; the server actually runs the generated root-level *.js. This change touches
    FOUR server modules, so four separate builds have to run -- src/server.ts alone is not enough.
    A commit made without rebuilding all four would look complete and deploy cleanly while changing
    nothing at runtime. STEP 4 re-reads each generated .js and asserts the new code is really in it,
    so a silently stale artifact fails HERE instead of shipping nothing. Same failure class the
    header of build_commit_deploy_takeworld_giveworld.ps1 documents.

    WHAT IT DOES
    ------------
      1. Sanity-checks both repo paths.
      2. Confirms every source edit is present (did the write-backs actually land?).
      3. Builds the four affected server modules, leaves first, server entry last.
      4. Verifies each generated .js really contains the new code (the stale-artifact guard).
      5. Commits ONLY the named files in each repo (never a blanket `git add -A`).
      6. Runs .\deploy_staging.ps1   (STAGING only -- see SAFETY)

    SAFETY
    ------
      * Never runs promote_staging_to_production.ps1. Staging only, by construction.
      * Only ever `git add`s an explicit list of files, so unrelated work-in-progress in either
        repo is never swept in.
      * Skips the commit step cleanly when a repo has nothing staged, so re-running after a
        partial failure (e.g. the deploy failed) is safe.
      * The Godot client changes are committed to the pixel-mania repo but are NOT shipped by
        deploy_staging.ps1 -- that only packages the backend. Run the client from the Godot editor
        to test them; players get them on the next client build/export.
      * -Push is off by default. Nothing is pushed to GitHub unless you ask for it.

    USAGE
        cd D:\Pixelmania\PixelMania\PixelManiaServer
        .\build_commit_deploy_place_item_loss_fix.ps1                 # build, commit both repos, deploy to staging
        .\build_commit_deploy_place_item_loss_fix.ps1 -DryRun         # show what would happen, change nothing
        .\build_commit_deploy_place_item_loss_fix.ps1 -SkipDeploy     # build + commit only
        .\build_commit_deploy_place_item_loss_fix.ps1 -Fast           # deploy with -Fast (skips local check:security preflight)
        .\build_commit_deploy_place_item_loss_fix.ps1 -Push           # also push each repo's current branch to origin
        .\build_commit_deploy_place_item_loss_fix.ps1 -SkipClient     # leave the pixel-mania repo alone
#>

param(
    [string]$ClientRepo = "D:\Pixelmania\PixelMania\pixel-mania",
    [string]$ServerMessage = "fix(net): queue authoritative packets under websocket backpressure instead of dropping them, and commit seed placement atomically",
    [string]$ClientMessage = "fix(world): reconcile unpredicted block places and seed plants so a lost server echo cannot consume the item",
    [switch]$SkipDeploy,
    [switch]$SkipClient,
    [switch]$DryRun,
    [switch]$Fast,
    [switch]$Push
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$ServerRepo = $PSScriptRoot

# Files this fix owns, per repo. Explicit lists on purpose -- see SAFETY above.
$ServerSources = @(
    "src/server_socket_delivery_helpers.ts",
    "src/server_phase8_world_action_routes.ts",
    "src/server_phase11a_runtime.ts",
    "src/server.ts",
    "build_commit_deploy_place_item_loss_fix.ps1"
)
# Generated by the builds below. Committed, because the server runs THESE, not src/*.ts.
$ServerArtifacts = @(
    "server_socket_delivery_helpers.js",
    "server_phase8_world_action_routes.js",
    "server_phase11a_runtime.js",
    "server.js"
)
$ClientFiles = @(
    "Scripts/block_manager.gd",
    "Scripts/world.gd",
    "Scripts/world_state_sync_manager.gd"
)

# Each affected module: npm build script, generated artifact, and a marker string that only
# exists after this change. String literals are used as markers wherever possible because they
# survive compilation verbatim.
$Modules = @(
    @{
        Name     = "socket delivery helpers"
        Script   = "build:server-socket-delivery-helpers"
        Artifact = "server_socket_delivery_helpers.js"
        Markers  = @("socket_backpressure_queued", "socket_backpressure_disconnect", "outbound_backpressure_forced")
    },
    @{
        Name     = "phase8 world action routes"
        Script   = "build:server-phase8-world-action-routes"
        Artifact = "server_phase8_world_action_routes.js"
        Markers  = @("PostgreSQL rejected the seed placement.", "seedPlayerState")
    },
    @{
        Name     = "phase11a runtime"
        Script   = "build:server-phase11a-runtime"
        Artifact = "server_phase11a_runtime.js"
        Markers  = @("outbound_backpressure_forced", "outbound_backpressure_disconnects")
    },
    @{
        Name     = "server entry"
        Script   = "build:server-entry"
        Artifact = "server.js"
        Markers  = @("SERVER_WEBSOCKET_CRITICAL_BUFFERED_AMOUNT", "authoritative_seed_present", "outbound_backpressure_disconnects")
    }
)

function Write-Step($text) {
    Write-Host ""
    Write-Host "=== $text ===" -ForegroundColor Cyan
}

function Assert-Contains($path, $needle, $why) {
    if (-not (Test-Path -LiteralPath $path)) { throw "Missing expected file: $path" }
    $content = Get-Content -LiteralPath $path -Raw
    if (-not $content.Contains($needle)) {
        throw "$path is missing '$needle' -- $why"
    }
}

# -------------------------------------------------------------------------------------------
Write-Step "1/6  Checking repo paths"
if (-not (Test-Path (Join-Path $ServerRepo "package.json"))) {
    throw "Run this from the PixelManiaServer folder (package.json not found in $ServerRepo)."
}
if (-not (Test-Path (Join-Path $ServerRepo "deploy_staging.ps1"))) {
    throw "Missing deploy_staging.ps1 in $ServerRepo"
}
if (-not $SkipClient -and -not (Test-Path (Join-Path $ClientRepo "project.godot"))) {
    throw "Client repo not found at $ClientRepo (pass -ClientRepo <path>, or -SkipClient)."
}
Write-Host "  Server: $ServerRepo" -ForegroundColor DarkGray
Write-Host "  Client: $ClientRepo" -ForegroundColor DarkGray

# -------------------------------------------------------------------------------------------
Write-Step "2/6  Confirming the source edits are present"
# Cheap, high-signal markers. If a write-back never landed or a file got reverted, this fails
# before spending time on four builds.
Assert-Contains (Join-Path $ServerRepo "src/server_socket_delivery_helpers.ts") "DEFAULT_DROPPABLE_PACKET_TYPES" `
    "the droppable-packet-type allowlist is missing; backpressure would still drop everything"
Assert-Contains (Join-Path $ServerRepo "src/server_socket_delivery_helpers.ts") "disconnectBackpressuredSocket" `
    "the hard-ceiling disconnect is missing"
Assert-Contains (Join-Path $ServerRepo "src/server.ts") "SERVER_WEBSOCKET_CRITICAL_BUFFERED_AMOUNT" `
    "the hard-ceiling constant is missing from the server entry"
Assert-Contains (Join-Path $ServerRepo "src/server.ts") "authoritative_seed_present" `
    "the seed reconciliation payload fields are missing"
Assert-Contains (Join-Path $ServerRepo "src/server_phase8_world_action_routes.ts") "deferred_inventory_commit" `
    "the atomic seed commit is missing from the world_seed_update route"
Assert-Contains (Join-Path $ServerRepo "src/server_phase11a_runtime.ts") "outbound_backpressure_forced" `
    "the new counters are missing from the stats snapshot allowlist and would be invisible"
if (-not $SkipClient) {
    Assert-Contains (Join-Path $ClientRepo "Scripts/block_manager.gd") "track_unpredicted_authoritative_place" `
        "tracking for placements the client does not predict is missing"
    Assert-Contains (Join-Path $ClientRepo "Scripts/block_manager.gd") "last_confirmed_place_visual_applied" `
        "the confirmed-place feedback flag is missing"
    Assert-Contains (Join-Path $ClientRepo "Scripts/world.gd") "handle_authoritative_seed_place_reconcile" `
        "the seed place reconciliation handler is missing"
    Assert-Contains (Join-Path $ClientRepo "Scripts/world.gd") "AUTHORITATIVE_SEED_PLACE_GIVE_UP_MS" `
        "the pending seed place give-up bound is missing"
    Assert-Contains (Join-Path $ClientRepo "Scripts/world_state_sync_manager.gd") "note_pending_authoritative_seed_place_removed" `
        "the seed removal note is missing from the sync manager"
}
Write-Host "  All source markers present." -ForegroundColor DarkGray

# -------------------------------------------------------------------------------------------
Write-Step "3/6  Building the four affected server modules"
# Leaves first, server entry last.
if ($DryRun) {
    foreach ($module in $Modules) {
        Write-Host "  [DryRun] would run: npm run $($module.Script)" -ForegroundColor DarkYellow
    }
} else {
    Push-Location $ServerRepo
    try {
        foreach ($module in $Modules) {
            Write-Host "  npm run $($module.Script)   ($($module.Name))" -ForegroundColor DarkGray
            npm run $($module.Script)
            if ($LASTEXITCODE -ne 0) { throw "FAILED: npm run $($module.Script)" }
        }
    } finally {
        Pop-Location
    }
    Write-Host "  All four builds passed." -ForegroundColor DarkGray
}

# -------------------------------------------------------------------------------------------
Write-Step "4/6  Verifying each generated .js actually contains the new code"
# THE GUARD. A green build does not prove the sync step wrote the new code into the files the
# server actually runs -- and with four modules there are four chances to ship a stale one.
if ($DryRun) {
    Write-Host "  [DryRun] skipping artifact verification (nothing was built)." -ForegroundColor DarkYellow
} else {
    foreach ($module in $Modules) {
        foreach ($marker in $module.Markers) {
            Assert-Contains (Join-Path $ServerRepo $($module.Artifact)) $marker `
                "STALE ARTIFACT: $($module.Artifact) was not regenerated. Run 'npm run $($module.Script)' and re-check."
        }
        Write-Host "  $($module.Artifact) is in sync with source." -ForegroundColor Green
    }
}

# -------------------------------------------------------------------------------------------
Write-Step "5/6  Committing (named files only)"

function Commit-Repo($repo, $files, $message, $label) {
    $existing = @()
    foreach ($f in $files) {
        if (Test-Path -LiteralPath (Join-Path $repo $f)) { $existing += $f }
        else { Write-Host "  skipping missing $label file: $f" -ForegroundColor DarkYellow }
    }
    if ($existing.Count -eq 0) {
        Write-Host "  Nothing to add for $label." -ForegroundColor DarkYellow
        return
    }

    if ($DryRun) {
        Write-Host "  [DryRun] would: git -C $repo add $($existing -join ' ')" -ForegroundColor DarkYellow
        Write-Host "  [DryRun] would: git -C $repo commit -m ""$message""" -ForegroundColor DarkYellow
        return
    }

    git -C $repo add -- $existing
    if ($LASTEXITCODE -ne 0) { throw "FAILED: git add in $repo" }

    # Nothing staged is a normal outcome when re-running after a partial failure, not an error.
    git -C $repo diff --cached --quiet -- $existing
    if ($LASTEXITCODE -eq 0) {
        # ${label} not $label -- PowerShell reads "$label:" as a scope-qualified variable.
        Write-Host "  ${label}: no changes staged, skipping commit." -ForegroundColor DarkGray
        return
    }

    git -C $repo commit -m $message
    if ($LASTEXITCODE -ne 0) { throw "FAILED: git commit in $repo" }
    Write-Host "  $label committed." -ForegroundColor Green
}

Commit-Repo $ServerRepo ($ServerSources + $ServerArtifacts) $ServerMessage "server"
if (-not $SkipClient) {
    Commit-Repo $ClientRepo $ClientFiles $ClientMessage "client"
} else {
    Write-Host "  -SkipClient set, leaving the client repo alone." -ForegroundColor DarkYellow
}

if ($Push -and -not $DryRun) {
    $reposToPush = @($ServerRepo)
    if (-not $SkipClient) { $reposToPush += $ClientRepo }
    foreach ($repo in $reposToPush) {
        $branch = (git -C $repo rev-parse --abbrev-ref HEAD).Trim()
        Write-Host "  pushing $repo ($branch) to origin" -ForegroundColor DarkGray
        git -C $repo push origin $branch
        if ($LASTEXITCODE -ne 0) { throw "FAILED: git push in $repo" }
    }
} elseif ($Push) {
    Write-Host "  [DryRun] would push each repo's current branch to origin." -ForegroundColor DarkYellow
}

# Surface anything else that is dirty, so an unrelated file is noticed rather than silently left
# behind (the deploy preflight refuses if anything else in the server repo is dirty).
if (-not $DryRun) {
    $dirty = git -C $ServerRepo status --porcelain
    if ($dirty) {
        Write-Host ""
        Write-Host "  NOTE: other uncommitted changes remain in the server repo:" -ForegroundColor DarkYellow
        $dirty | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkYellow }
        Write-Host "  If any are GENERATED .js files, the deploy preflight will refuse until they are" -ForegroundColor DarkYellow
        Write-Host "  committed. Anything else (e.g. other in-progress work) is fine to leave." -ForegroundColor DarkYellow
    }
}

# -------------------------------------------------------------------------------------------
Write-Step "6/6  Deploying to STAGING"

# deploy_to_droplet.ps1's Assert-LocalPreflightPreservedBackendCommit demands the backend repo be
# COMPLETELY clean -- no tracked diff vs HEAD, and no untracked files at all. Checking it HERE
# turns that into a clear, actionable message instead of an exception thrown from deep inside
# deploy_to_droplet.ps1.
if (-not $DryRun) {
    $trackedDirty = git -C $ServerRepo diff --name-only HEAD --
    $untracked = git -C $ServerRepo ls-files --others --exclude-standard
    if ($trackedDirty -or $untracked) {
        Write-Host ""
        Write-Host "  Backend repo is not clean, so the deploy would refuse:" -ForegroundColor Red
        if ($trackedDirty) {
            Write-Host "    modified (tracked):" -ForegroundColor Red
            $trackedDirty | ForEach-Object { Write-Host "      $_" -ForegroundColor Red }
        }
        if ($untracked) {
            Write-Host "    untracked:" -ForegroundColor Red
            $untracked | ForEach-Object { Write-Host "      $_" -ForegroundColor Red }
        }
        Write-Host ""
        Write-Host "  Commit them, or add them to .gitignore if they are scratch files:" -ForegroundColor Yellow
        Write-Host "      git -C `"$ServerRepo`" add -A"
        Write-Host "      git -C `"$ServerRepo`" commit -m ""chore: commit remaining backend files before deploy"""
        Write-Host ""
        Write-Host "  Careful with 'add -A' if you have work-in-progress you do NOT want committed" -ForegroundColor Yellow
        Write-Host "  -- add those to .gitignore or stash them instead." -ForegroundColor Yellow
        throw "Backend repo not clean; refusing to start the deploy."
    }
    Write-Host "  Backend repo is clean." -ForegroundColor DarkGray
}

if ($SkipDeploy) {
    Write-Host "  -SkipDeploy set. Deploy manually with:  .\deploy_staging.ps1" -ForegroundColor Yellow
} elseif ($DryRun) {
    Write-Host "  [DryRun] would run: .\deploy_staging.ps1" -ForegroundColor DarkYellow
} else {
    Push-Location $ServerRepo
    try {
        # Staging only. This script never calls promote_staging_to_production.ps1.
        if ($Fast) { .\deploy_staging.ps1 -Fast } else { .\deploy_staging.ps1 }
        if ($LASTEXITCODE -ne 0) { throw "FAILED: deploy_staging.ps1" }
    } finally {
        Pop-Location
    }
    Write-Host "  Deployed to staging." -ForegroundColor Green
}

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host ""
Write-Host "This only deployed the BACKEND to staging. The three .gd changes are committed but not" -ForegroundColor Yellow
Write-Host "shipped by this script -- run the client from the Godot editor against staging to test" -ForegroundColor Yellow
Write-Host "them, and build/export the client when you want players to have them." -ForegroundColor Yellow
Write-Host ""
Write-Host "Verify on staging, in this order:" -ForegroundColor Yellow
Write-Host "  1. Place blocks and plant seeds normally -> no visible change, no double particles,"
Write-Host "     inventory counts still match after each action."
Write-Host "  2. Place a World Lock / Small Lock and a water bucket (the un-predicted paths)"
Write-Host "     -> they still appear and are still charged exactly once."
Write-Host "  3. Throttle the client's connection (Clumsy, or a phone on a weak signal), then"
Write-Host "     place a block and plant a seed -> both eventually appear, and no item is lost."
Write-Host "  4. Harvest a seed and immediately replant on the same tile -> the new plant survives."
Write-Host ""
Write-Host "Watch for these in the staging logs:" -ForegroundColor Yellow
Write-Host "    sudo -u pixelmania-stg pm2 logs --lines 200 --nostream"
Write-Host "  [socket_backpressure_queued]     -- the new path working (was a silent drop before)"
Write-Host "  [socket_backpressure_skip]       -- should now only ever name player_position_batch"
Write-Host "  [socket_backpressure_disconnect] -- hard ceiling hit; if this is common, that client"
Write-Host "                                      was never going to receive its state anyway, but"
Write-Host "                                      a burst of them means the ceiling is too low."
Write-Host "  The same three are counted in the health/stats snapshot as outbound_backpressure_"
Write-Host "  forced / _skips / _disconnects."
Write-Host ""
Write-Host "When staging looks good:  .\promote_staging_to_production.ps1" -ForegroundColor Yellow
