<#
    PixelMania - one-command build + commit + deploy for the /takeworld and /giveworld
    developer-only world-ownership override commands.

    WHY THIS EXISTS
    ---------------
    src/server.ts is source; the server actually runs server.js, which is GENERATED by
    `npm run build:server-entry`. This session edited src/server.ts directly and could not run
    that build (no shell access to this machine from the cloud sandbox), so server.js on disk
    right now still has the OLD behavior. A commit made without rebuilding would look complete
    and deploy cleanly while changing nothing at runtime -- see server_build_process.md /
    [[server-build-process]] in project memory, and the exact same failure class documented in
    build_commit_deploy_landfill.ps1.

    So this script does not just chain commands. After building, it re-reads server.js and
    asserts the new code is actually in it (STEP 4). If the build silently produced a stale
    artifact, it fails HERE, loudly, instead of shipping nothing.

    WHAT IT DOES
    ------------
      1. Sanity-checks both repo paths.
      2. Confirms the takeworld/giveworld source edits are present in src/server.ts and
         Scripts/command_manager.gd (did the edits actually land on this machine?).
      3. npm run build:server-entry   -- rebuilds server.js from src/server.ts.
      4. Verifies server.js really contains the new code (the stale-artifact guard).
      5. Commits ONLY the named files in each repo (never a blanket `git add -A`).
      6. Runs .\deploy_staging.ps1   (STAGING only -- see SAFETY)

    SAFETY
    ------
      * Never runs promote_staging_to_production.ps1. Staging only, by construction. Promote to
        production yourself once you've verified this on staging -- see deploy_environment_rules.md.
      * Only ever `git add`s an explicit list of files. It will never sweep in unrelated
        work-in-progress sitting in either repo.
      * Skips the commit step cleanly when a repo has nothing staged, so re-running after a
        partial failure (e.g. deploy failed) is safe.
      * The Godot client change (command_manager.gd) is committed to the pixel-mania repo but is
        NOT shipped by deploy_staging.ps1 -- that only packages the backend. Players only get the
        new /takeworld and /giveworld commands after you build/export the Godot client and they
        update. To test immediately, just run the client from the Godot editor.

    USAGE
        cd G:\PixelMania\PixelManiaServer
        .\build_commit_deploy_takeworld_giveworld.ps1                 # build, commit both repos, deploy to staging
        .\build_commit_deploy_takeworld_giveworld.ps1 -SkipDeploy     # build + commit only
        .\build_commit_deploy_takeworld_giveworld.ps1 -DryRun         # show what would happen, change nothing
        .\build_commit_deploy_takeworld_giveworld.ps1 -Fast           # deploy with -Fast (skips local check:security preflight)
        .\build_commit_deploy_takeworld_giveworld.ps1 -SkipClient     # leave the pixel-mania repo alone
#>

param(
    [string]$ClientRepo = "G:\PixelMania\pixel-mania",
    [string]$ServerMessage = "feat(admin): add /takeworld and /giveworld developer-only world ownership override commands",
    [string]$ClientMessage = "feat(commands): wire /takeworld and /giveworld, developer-only",
    [switch]$SkipDeploy,
    [switch]$SkipClient,
    [switch]$DryRun,
    [switch]$Fast
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$ServerRepo = $PSScriptRoot

# Files this feature owns, per repo. Explicit lists on purpose -- see SAFETY above.
$ServerSources = @(
    "src/server.ts",
    "build_commit_deploy_takeworld_giveworld.ps1"
)
# Generated by the build. Committed, because the server runs THIS, not src/server.ts.
$ServerArtifacts = @(
    "server.js"
)
$ClientFiles = @(
    "Scripts/command_manager.gd"
)

function Write-Step($text) {
    Write-Host ""
    Write-Host "=== $text ===" -ForegroundColor Cyan
}

function Assert-Contains($path, $needle, $why) {
    if (-not (Test-Path -LiteralPath $path)) { throw "Missing expected file: $path" }
    $content = Get-Content -LiteralPath $path -Raw
    if (-not $content.Contains($needle)) {
        throw "$path is missing '$needle' -- $why"
    }
}

# -------------------------------------------------------------------------------------------
Write-Step "1/6  Checking repo paths"
if (-not (Test-Path (Join-Path $ServerRepo "package.json"))) {
    throw "Run this from the PixelManiaServer folder (package.json not found in $ServerRepo)."
}
if (-not (Test-Path (Join-Path $ServerRepo "deploy_staging.ps1"))) {
    throw "Missing deploy_staging.ps1 in $ServerRepo"
}
if (-not $SkipClient -and -not (Test-Path (Join-Path $ClientRepo "project.godot"))) {
    throw "Client repo not found at $ClientRepo (pass -ClientRepo <path>, or -SkipClient)."
}
Write-Host "  Server: $ServerRepo" -ForegroundColor DarkGray
Write-Host "  Client: $ClientRepo" -ForegroundColor DarkGray

# -------------------------------------------------------------------------------------------
Write-Step "2/6  Confirming the takeworld/giveworld source edits are present"
# Cheap, high-signal markers. If a file got reverted or a write-back never landed, this fails
# before spending time on a build.
Assert-Contains (Join-Path $ServerRepo "src/server.ts") "parseTakeWorldCommand" `
    "the /takeworld server handler is missing"
Assert-Contains (Join-Path $ServerRepo "src/server.ts") "parseGiveWorldCommand" `
    "the /giveworld server handler is missing"
Assert-Contains (Join-Path $ServerRepo "src/server.ts") "developer_take_world" `
    "the /takeworld command_type response is missing"
Assert-Contains (Join-Path $ServerRepo "src/server.ts") "developer_give_world" `
    "the /giveworld command_type response is missing"
if (-not $SkipClient) {
    Assert-Contains (Join-Path $ClientRepo "Scripts/command_manager.gd") "parse_take_world_arguments" `
        "the client-side /takeworld parsing is missing"
    Assert-Contains (Join-Path $ClientRepo "Scripts/command_manager.gd") "parse_give_world_arguments" `
        "the client-side /giveworld parsing is missing"
}
Write-Host "  All source markers present." -ForegroundColor DarkGray

# -------------------------------------------------------------------------------------------
Write-Step "3/6  Building server.js from src/server.ts"
if ($DryRun) {
    Write-Host "  [DryRun] would run: npm run build:server-entry" -ForegroundColor DarkYellow
} else {
    Push-Location $ServerRepo
    try {
        npm run build:server-entry
        if ($LASTEXITCODE -ne 0) { throw "FAILED: npm run build:server-entry" }
    } finally {
        Pop-Location
    }
    Write-Host "  Build passed." -ForegroundColor DarkGray
}

# -------------------------------------------------------------------------------------------
Write-Step "4/6  Verifying server.js actually contains the new code"
# THE GUARD. This is the whole reason this script exists -- see the header. A green build above
# does not prove the sync step wrote the new code into the file the server actually runs.
if ($DryRun) {
    Write-Host "  [DryRun] skipping artifact verification (nothing was built)." -ForegroundColor DarkYellow
} else {
    Assert-Contains (Join-Path $ServerRepo "server.js") "parseTakeWorldCommand" `
        "STALE ARTIFACT: the build did not regenerate server.js. Run 'npm run build:server-entry' and re-check."
    Assert-Contains (Join-Path $ServerRepo "server.js") "parseGiveWorldCommand" `
        "STALE ARTIFACT: /giveworld is not in the file the server actually runs."
    Write-Host "  server.js is in sync with source." -ForegroundColor Green
}

# -------------------------------------------------------------------------------------------
Write-Step "5/6  Committing (named files only)"

function Commit-Repo($repo, $files, $message, $label) {
    $existing = @()
    foreach ($f in $files) {
        if (Test-Path -LiteralPath (Join-Path $repo $f)) { $existing += $f }
        else { Write-Host "  skipping missing $label file: $f" -ForegroundColor DarkYellow }
    }
    if ($existing.Count -eq 0) {
        Write-Host "  Nothing to add for $label." -ForegroundColor DarkYellow
        return
    }

    if ($DryRun) {
        Write-Host "  [DryRun] would: git -C $repo add $($existing -join ' ')" -ForegroundColor DarkYellow
        Write-Host "  [DryRun] would: git -C $repo commit -m ""$message""" -ForegroundColor DarkYellow
        return
    }

    git -C $repo add -- $existing
    if ($LASTEXITCODE -ne 0) { throw "FAILED: git add in $repo" }

    # Nothing staged is a normal outcome when re-running after a partial failure, not an error.
    git -C $repo diff --cached --quiet -- $existing
    if ($LASTEXITCODE -eq 0) {
        # ${label} not $label -- PowerShell treats "$label:" as a SCOPE-qualified variable
        # reference (the same syntax as $global:x / $env:PATH), so the colon has to be pushed
        # outside the name with braces or the file fails to parse at all.
        Write-Host "  ${label}: no changes staged, skipping commit." -ForegroundColor DarkGray
        return
    }

    git -C $repo commit -m $message
    if ($LASTEXITCODE -ne 0) { throw "FAILED: git commit in $repo" }
    Write-Host "  $label committed." -ForegroundColor Green
}

Commit-Repo $ServerRepo ($ServerSources + $ServerArtifacts) $ServerMessage "server"
if (-not $SkipClient) {
    Commit-Repo $ClientRepo $ClientFiles $ClientMessage "client"
} else {
    Write-Host "  -SkipClient set, leaving the client repo alone." -ForegroundColor DarkYellow
}

# Surface anything else that is dirty, so an unrelated file is noticed rather than silently left
# behind (the deploy preflight refuses if anything else in the server repo is dirty).
if (-not $DryRun) {
    $dirty = git -C $ServerRepo status --porcelain
    if ($dirty) {
        Write-Host ""
        Write-Host "  NOTE: other uncommitted changes remain in the server repo:" -ForegroundColor DarkYellow
        $dirty | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkYellow }
        Write-Host "  If any are GENERATED .js files, the deploy preflight will refuse until they are" -ForegroundColor DarkYellow
        Write-Host "  committed. Anything else (e.g. other in-progress work) is fine to leave." -ForegroundColor DarkYellow
    }
}

# -------------------------------------------------------------------------------------------
Write-Step "6/6  Deploying to STAGING"

# deploy_to_droplet.ps1's Assert-LocalPreflightPreservedBackendCommit demands the backend repo be
# COMPLETELY clean -- no tracked diff vs HEAD, and no untracked files at all:
#
#     $trackedDiff   = git diff --name-only HEAD --
#     $untrackedFiles = git ls-files --others --exclude-standard
#     if ($trackedDiff -or $untrackedFiles) { throw ... }
#
# Checking it HERE turns that into a clear, actionable message instead of an exception thrown
# from deep inside deploy_to_droplet.ps1 with a stack trace attached.
if (-not $DryRun) {
    $trackedDirty = git -C $ServerRepo diff --name-only HEAD --
    $untracked = git -C $ServerRepo ls-files --others --exclude-standard
    if ($trackedDirty -or $untracked) {
        Write-Host ""
        Write-Host "  Backend repo is not clean, so the deploy would refuse:" -ForegroundColor Red
        if ($trackedDirty) {
            Write-Host "    modified (tracked):" -ForegroundColor Red
            $trackedDirty | ForEach-Object { Write-Host "      $_" -ForegroundColor Red }
        }
        if ($untracked) {
            Write-Host "    untracked:" -ForegroundColor Red
            $untracked | ForEach-Object { Write-Host "      $_" -ForegroundColor Red }
        }
        Write-Host ""
        Write-Host "  Commit them, or add them to .gitignore if they are scratch files:" -ForegroundColor Yellow
        Write-Host "      git -C `"$ServerRepo`" add -A"
        Write-Host "      git -C `"$ServerRepo`" commit -m ""chore: commit remaining backend files before deploy"""
        Write-Host ""
        Write-Host "  Careful with 'add -A' if you have work-in-progress you do NOT want committed" -ForegroundColor Yellow
        Write-Host "  -- add those to .gitignore or stash them instead." -ForegroundColor Yellow
        throw "Backend repo not clean; refusing to start the deploy."
    }
    Write-Host "  Backend repo is clean." -ForegroundColor DarkGray
}

if ($SkipDeploy) {
    Write-Host "  -SkipDeploy set. Deploy manually with:  .\deploy_staging.ps1" -ForegroundColor Yellow
} elseif ($DryRun) {
    Write-Host "  [DryRun] would run: .\deploy_staging.ps1" -ForegroundColor DarkYellow
} else {
    Push-Location $ServerRepo
    try {
        # Staging only. This script never calls promote_staging_to_production.ps1.
        if ($Fast) { .\deploy_staging.ps1 -Fast } else { .\deploy_staging.ps1 }
        if ($LASTEXITCODE -ne 0) { throw "FAILED: deploy_staging.ps1" }
    } finally {
        Pop-Location
    }
    Write-Host "  Deployed to staging." -ForegroundColor Green
}

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host ""
Write-Host "This only deployed the BACKEND to staging. The client change (command_manager.gd) is" -ForegroundColor Yellow
Write-Host "committed but not shipped by this script -- run/export the Godot client to test it, and" -ForegroundColor Yellow
Write-Host "when you're ready for players to have it, do a normal client build/update." -ForegroundColor Yellow
Write-Host ""
Write-Host "Verify on staging (as the uso account) in this order:" -ForegroundColor Yellow
Write-Host "  1. Lock a test world under a DIFFERENT account, then /takeworld that_world as uso"
Write-Host "     -> chat confirms ownership taken; the world lock UI now shows uso as owner"
Write-Host "  2. /giveworld that_world some_other_account as uso"
Write-Host "     -> chat confirms; the other account now shows as owner"
Write-Host "  3. Try /takeworld or /giveworld from a non-uso admin/designer account -> denied"
Write-Host "  4. /takeworld an_unlocked_world_name -> denied (nothing to take)"
Write-Host ""
Write-Host "If something misbehaves:" -ForegroundColor Yellow
Write-Host "    sudo -u pixelmania-stg pm2 logs --lines 100 --nostream"
Write-Host "  Look for [developer_command_exception] or developer_take_world / developer_give_world."
