param(
  [Parameter(Mandatory = $true, Position = 0)]
  [string]$RemoteIp,

  [string]$RemoteUser = "pixelmania",
  [string]$RemoteDir = "PixelManiaServer",
  [string]$SshKeyPath,
  [string]$OpsDashboardToken,
  [string]$OpsDashboardTokenHash,
  [string]$OpsDashboardAdminUsername = "admin",
  [string]$OpsDashboardAdminEmail = "",
  [string]$OpsDashboardAdminPassword,
  [string]$OpsDashboardAdminPasswordHash,
  [int]$OpsDashboardPort = 9090,
  [string]$HealthUrl = "http://127.0.0.1:8080/health"
)

$ErrorActionPreference = "Stop"

function ConvertTo-ShellLiteral {
  param([string]$Value)
  return "'" + $Value.Replace("'", "'\''") + "'"
}

function Get-Sha256Hex {
  param([string]$Value)
  $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
  $hash = [System.Security.Cryptography.SHA256]::Create().ComputeHash($bytes)
  return (($hash | ForEach-Object { $_.ToString("x2") }) -join "")
}

function New-Base64UrlToken {
  $bytes = New-Object byte[] 32
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  } finally {
    $rng.Dispose()
  }
  return [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
}

function Get-OpsDashboardPasswordHash {
  param([string]$Password)
  $helper = Join-Path $PSScriptRoot "scripts/generate_ops_dashboard_password_hash.js"
  if (-not (Test-Path -LiteralPath $helper)) {
    throw "Missing password hash helper: $helper"
  }
  $output = & node $helper $Password
  if ($LASTEXITCODE -ne 0) {
    throw "Password hash helper failed."
  }
  $line = $output | Where-Object { $_ -like "OPS_DASHBOARD_ADMIN_PASSWORD_HASH=*" } | Select-Object -First 1
  if (-not $line) {
    throw "Password hash helper did not print OPS_DASHBOARD_ADMIN_PASSWORD_HASH."
  }
  return $line.Substring("OPS_DASHBOARD_ADMIN_PASSWORD_HASH=".Length)
}

if (-not $OpsDashboardAdminPassword -and -not $OpsDashboardAdminPasswordHash) {
  $OpsDashboardAdminPassword = New-Base64UrlToken
  Write-Host ""
  Write-Host "Generated PixelMania Ops admin password. Save it now; only the hash will be installed on the server:"
  Write-Host "username: $OpsDashboardAdminUsername"
  Write-Host "password: $OpsDashboardAdminPassword"
  Write-Host ""
}

if ($OpsDashboardAdminPassword) {
  $OpsDashboardAdminPasswordHash = Get-OpsDashboardPasswordHash $OpsDashboardAdminPassword
}

if (-not ($OpsDashboardAdminPasswordHash -match "^scrypt:[0-9]+:[0-9]+:[0-9]+:[A-Za-z0-9_-]+:[a-fA-F0-9]+$")) {
  throw "OpsDashboardAdminPasswordHash must be generated by scripts/generate_ops_dashboard_password_hash.js."
}

if ($OpsDashboardToken) {
  $computedHash = Get-Sha256Hex $OpsDashboardToken
  if ($OpsDashboardTokenHash -and $OpsDashboardTokenHash.ToLowerInvariant() -ne $computedHash) {
    throw "OpsDashboardTokenHash does not match OpsDashboardToken."
  }
  $OpsDashboardTokenHash = $computedHash
}

if ($OpsDashboardTokenHash -and -not ($OpsDashboardTokenHash -match "^[a-fA-F0-9]{64}$")) {
  throw "OpsDashboardTokenHash must be a 64-character sha256 hex string."
}

if ($OpsDashboardPort -lt 1 -or $OpsDashboardPort -gt 65535) {
  throw "OpsDashboardPort must be between 1 and 65535."
}

if (-not $SshKeyPath -and $env:PIXELMANIA_SSH_KEY) {
  $SshKeyPath = $env:PIXELMANIA_SSH_KEY
}

if (-not $SshKeyPath) {
  $defaultSshKeyPath = Join-Path $HOME ".ssh/pixelmania_ed25519"
  if (Test-Path -LiteralPath $defaultSshKeyPath) {
    $SshKeyPath = $defaultSshKeyPath
  }
}

if ($SshKeyPath) {
  if (-not (Test-Path -LiteralPath $SshKeyPath)) {
    throw "SSH key not found: $SshKeyPath"
  }
  Write-Host "Using SSH key: $SshKeyPath"
  $sshBaseArgs = @("-i", $SshKeyPath, "-o", "BatchMode=yes")
} else {
  $sshBaseArgs = @()
}

$localOpsDashboardServer = Join-Path $PSScriptRoot "ops_dashboard_server.js"
$localOpsDashboardEcosystem = Join-Path $PSScriptRoot "ecosystem.ops.config.js"
$localOpsDashboardPublic = Join-Path $PSScriptRoot "ops_dashboard_public"
$localOpsDashboardEnvExample = Join-Path $PSScriptRoot ".env.ops.example"
$localOpsDashboardDoc = Join-Path $PSScriptRoot "docs/ops_dashboard.md"
$localOpsDashboardTokenHelper = Join-Path $PSScriptRoot "scripts/generate_ops_dashboard_token_hash.js"
$localOpsDashboardPasswordHelper = Join-Path $PSScriptRoot "scripts/generate_ops_dashboard_password_hash.js"
$localRouteProductionSetup = Join-Path $PSScriptRoot "scripts/start_route_production_instances.sh"
$localOpsDashboardGitDeploy = Join-Path $PSScriptRoot "scripts/ops_dashboard_git_deploy.sh"
$localOpsDashboardGitRollback = Join-Path $PSScriptRoot "scripts/ops_dashboard_git_rollback.sh"
$localOpsDashboardAccountBackup = Join-Path $PSScriptRoot "scripts/ops_dashboard_account_backup.sh"
$localOpsDashboardBackupCron = Join-Path $PSScriptRoot "scripts/install_ops_dashboard_backup_cron.sh"
$localOpsDashboardHttps = Join-Path $PSScriptRoot "scripts/install_ops_dashboard_https.sh"

foreach ($path in @($localOpsDashboardServer, $localOpsDashboardEcosystem, $localOpsDashboardEnvExample, $localOpsDashboardDoc, $localOpsDashboardTokenHelper, $localOpsDashboardPasswordHelper, $localRouteProductionSetup, $localOpsDashboardGitDeploy, $localOpsDashboardGitRollback, $localOpsDashboardAccountBackup, $localOpsDashboardBackupCron, $localOpsDashboardHttps)) {
  if (-not (Test-Path -LiteralPath $path)) {
    throw "Missing file: $path"
  }
}
if (-not (Test-Path -LiteralPath $localOpsDashboardPublic)) {
  throw "Missing directory: $localOpsDashboardPublic"
}

$sshTarget = "${RemoteUser}@${RemoteIp}"
$remotePath = "~/$RemoteDir"

function Invoke-RemoteCommand {
  param([string]$Command)
  & ssh @sshBaseArgs "$sshTarget" $Command
  if ($LASTEXITCODE -ne 0) {
    throw "Remote command failed with exit code $LASTEXITCODE"
  }
}

Write-Host "Copying PixelMania ops dashboard files to ${sshTarget}:${remotePath}..."
Invoke-RemoteCommand "mkdir -p $remotePath/scripts $remotePath/docs $remotePath/ops_dashboard_public"
& scp @sshBaseArgs $localOpsDashboardServer "${sshTarget}:$remotePath/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard server." }
& scp @sshBaseArgs $localOpsDashboardEcosystem "${sshTarget}:$remotePath/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard PM2 config." }
& scp @sshBaseArgs $localOpsDashboardEnvExample "${sshTarget}:$remotePath/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard env example." }
& scp @sshBaseArgs -r $localOpsDashboardPublic "${sshTarget}:$remotePath/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard public files." }
& scp @sshBaseArgs $localOpsDashboardDoc "${sshTarget}:$remotePath/docs/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard docs." }
& scp @sshBaseArgs $localOpsDashboardTokenHelper "${sshTarget}:$remotePath/scripts/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard token helper." }
& scp @sshBaseArgs $localOpsDashboardPasswordHelper "${sshTarget}:$remotePath/scripts/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard password helper." }
& scp @sshBaseArgs $localRouteProductionSetup "${sshTarget}:$remotePath/scripts/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for route production helper." }
& scp @sshBaseArgs $localOpsDashboardGitDeploy "${sshTarget}:$remotePath/scripts/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard git deploy helper." }
& scp @sshBaseArgs $localOpsDashboardGitRollback "${sshTarget}:$remotePath/scripts/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard git rollback helper." }
& scp @sshBaseArgs $localOpsDashboardAccountBackup "${sshTarget}:$remotePath/scripts/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard account backup helper." }
& scp @sshBaseArgs $localOpsDashboardBackupCron "${sshTarget}:$remotePath/scripts/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard account backup cron helper." }
& scp @sshBaseArgs $localOpsDashboardHttps "${sshTarget}:$remotePath/scripts/"
if ($LASTEXITCODE -ne 0) { throw "scp failed for ops dashboard HTTPS helper." }

$hashLiteral = ConvertTo-ShellLiteral $(if ($OpsDashboardTokenHash) { $OpsDashboardTokenHash.ToLowerInvariant() } else { "" })
$adminUsernameLiteral = ConvertTo-ShellLiteral $OpsDashboardAdminUsername
$adminEmailLiteral = ConvertTo-ShellLiteral $OpsDashboardAdminEmail
$adminPasswordHashLiteral = ConvertTo-ShellLiteral $OpsDashboardAdminPasswordHash
$publicBaseUrlLiteral = ConvertTo-ShellLiteral "http://127.0.0.1:$OpsDashboardPort"
$portRaw = [string]$OpsDashboardPort
$healthLiteral = ConvertTo-ShellLiteral $HealthUrl

$remoteCommand = @'
set -euo pipefail
cd __REMOTE_PATH__

set_env() {
  key="$1"
  value="$2"
  touch .env
  if grep -qE "^${key}=" .env; then
    escaped_value="$(printf '%s' "$value" | sed 's/[\/&]/\\&/g')"
    sed -i "s/^${key}=.*/${key}=${escaped_value}/" .env
  else
    printf '\n%s=%s\n' "$key" "$value" >> .env
  fi
}

set_env OPS_DASHBOARD_HOST 127.0.0.1
set_env OPS_DASHBOARD_PORT __OPS_PORT__
set_env OPS_DASHBOARD_TOKEN ""
set_env OPS_DASHBOARD_TOKEN_HASH __OPS_HASH__
set_env OPS_DASHBOARD_ADMIN_USERNAME __OPS_ADMIN_USERNAME__
set_env OPS_DASHBOARD_ADMIN_EMAIL __OPS_ADMIN_EMAIL__
set_env OPS_DASHBOARD_ADMIN_PASSWORD_HASH __OPS_ADMIN_PASSWORD_HASH__
set_env OPS_DASHBOARD_ACCOUNT_FILE ""
set_env OPS_DASHBOARD_SESSION_TTL_HOURS 12
set_env OPS_DASHBOARD_COOKIE_SECURE false
set_env OPS_DASHBOARD_PUBLIC_BASE_URL __OPS_PUBLIC_BASE_URL__
set_env OPS_DASHBOARD_EMAIL_VERIFICATION_TTL_MINUTES 60
set_env OPS_DASHBOARD_PASSWORD_RESET_TTL_MINUTES 30
set_env OPS_DASHBOARD_MIN_PASSWORD_LENGTH 10
set_env OPS_DASHBOARD_LOGIN_CODE_ENABLED false
set_env OPS_DASHBOARD_LOGIN_CODE_TTL_MINUTES 10
set_env OPS_DASHBOARD_ACCOUNT_BACKUP_DIR /var/backups/pixelmania/ops-dashboard
set_env OPS_DASHBOARD_ACCOUNT_BACKUP_RETENTION_DAYS 30
set_env OPS_DASHBOARD_ACCOUNT_BACKUP_SCHEDULE "17 * * * *"
set_env OPS_DASHBOARD_DOMAIN ops.pixelmaniagame.com
set_env OPS_DASHBOARD_HEALTH_URL __HEALTH_URL__
set_env OPS_DASHBOARD_ROUTE_TARGETS "ws-a|pixelmania-a|http://127.0.0.1:18091/health|wss://api.pixelmaniagame.com/ws-a;ws-b|pixelmania-b|http://127.0.0.1:18092/health|wss://api.pixelmaniagame.com/ws-b"
set_env OPS_DASHBOARD_PM2_APP pixelmania
set_env OPS_DASHBOARD_PM2_ECOSYSTEM ecosystem.config.js
set_env OPS_DASHBOARD_ALLOW_CONTROL false
set_env OPS_DASHBOARD_ALLOWED_ACTIONS restart
set_env OPS_DASHBOARD_RESTART_APPS pixelmania,pixelmania-a,pixelmania-b
set_env OPS_DASHBOARD_RESTART_COMMAND "pm2 startOrReload ecosystem.config.js --env production --update-env && bash scripts/start_route_production_instances.sh"
set_env OPS_DASHBOARD_START_COMMAND "pm2 startOrReload ecosystem.config.js --env production --update-env && bash scripts/start_route_production_instances.sh"
set_env OPS_DASHBOARD_STOP_COMMAND 'for app in pixelmania pixelmania-a pixelmania-b; do pm2 stop "$app" || true; done; pm2 save'
set_env OPS_DASHBOARD_ALLOW_STOP_WITH_PLAYERS false
set_env OPS_DASHBOARD_ALLOW_DEPLOY_WITH_PLAYERS false
set_env OPS_DASHBOARD_ALLOW_ROLLBACK_WITH_PLAYERS false
set_env OPS_DASHBOARD_CONFIRM_ACTIONS stop,deploy,rollback
set_env OPS_DASHBOARD_ROLLBACK_COMMAND "bash scripts/ops_dashboard_git_rollback.sh"

node --check ops_dashboard_server.js
node --check ecosystem.ops.config.js
node --check scripts/generate_ops_dashboard_token_hash.js
node --check scripts/generate_ops_dashboard_password_hash.js
chmod +x scripts/start_route_production_instances.sh scripts/ops_dashboard_git_deploy.sh scripts/ops_dashboard_git_rollback.sh scripts/ops_dashboard_account_backup.sh scripts/install_ops_dashboard_backup_cron.sh scripts/install_ops_dashboard_https.sh
bash -n scripts/start_route_production_instances.sh
bash -n scripts/ops_dashboard_git_deploy.sh
bash -n scripts/ops_dashboard_git_rollback.sh
bash -n scripts/ops_dashboard_account_backup.sh
bash -n scripts/install_ops_dashboard_backup_cron.sh
bash -n scripts/install_ops_dashboard_https.sh
pm2 startOrReload ecosystem.ops.config.js --env production --update-env
pm2 save

echo "== pixelmania-ops status =="
pm2 describe pixelmania-ops

echo "== local dashboard auth check =="
status_code="$(curl -sS -o /tmp/pixelmania-ops-auth.json -w '%{http_code}' http://127.0.0.1:__OPS_PORT__/api/status || true)"
cat /tmp/pixelmania-ops-auth.json || true
echo
if [ "$status_code" != "401" ]; then
  echo "Expected unauthenticated /api/status to return 401, got ${status_code}."
  exit 1
fi

echo "PixelMania ops dashboard is running read-only on 127.0.0.1:__OPS_PORT__."
'@

$remoteCommand = $remoteCommand.
  Replace("__REMOTE_PATH__", $remotePath).
  Replace("__OPS_HASH__", $hashLiteral).
  Replace("__OPS_ADMIN_USERNAME__", $adminUsernameLiteral).
  Replace("__OPS_ADMIN_EMAIL__", $adminEmailLiteral).
  Replace("__OPS_ADMIN_PASSWORD_HASH__", $adminPasswordHashLiteral).
  Replace("__OPS_PUBLIC_BASE_URL__", $publicBaseUrlLiteral).
  Replace("__OPS_PORT__", $portRaw).
  Replace("__HEALTH_URL__", $healthLiteral)

$remoteBootstrap = "$remotePath/scripts/deploy_ops_dashboard_readonly_remote.sh"
$tempBootstrap = Join-Path ([System.IO.Path]::GetTempPath()) ("pixelmania-ops-dashboard-" + [guid]::NewGuid().ToString("N") + ".sh")
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($tempBootstrap, $remoteCommand, $utf8NoBom)
try {
  & scp @sshBaseArgs $tempBootstrap "${sshTarget}:$remoteBootstrap"
  if ($LASTEXITCODE -ne 0) { throw "scp failed for remote ops dashboard bootstrap." }
  Invoke-RemoteCommand "chmod +x $remoteBootstrap && bash $remoteBootstrap"
} finally {
  Remove-Item -LiteralPath $tempBootstrap -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "Read-only PixelMania ops dashboard is deployed."
Write-Host "Open it with an SSH tunnel:"
Write-Host "ssh -L ${OpsDashboardPort}:127.0.0.1:${OpsDashboardPort} ${sshTarget}"
Write-Host "Then browse to http://127.0.0.1:${OpsDashboardPort}"
