const path = require("path");
require("dotenv").config({ path: path.join(__dirname, ".env"), quiet: true });

module.exports = {
  apps: [
    {
      name: "pixelmania-a",
      script: "server.js",
      cwd: __dirname,
      exec_mode: "fork",
      instances: 1,
      watch: false,
      time: true,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",
        REDIS_ENABLED: "true",
        POSTGRES_ENABLED: "true",
        POSTGRES_AUTHORITATIVE: "true",
        ALLOW_AUTHORITATIVE_JSON_FALLBACK: "false",
        REQUIRE_POSTGRES_AUTHORITATIVE_FOR_GAMEPLAY: "true",
        WORLD_ROUTE_ENFORCEMENT_ENABLED: "true",
        REDIS_REQUIRED_FOR_ROUTE_ENFORCEMENT: "true",
        WORLD_ROUTE_TTL_MS: "45000",
        WORLD_ADMISSION_TTL_MS: "45000",
        MAX_PLAYERS_PER_WORLD: "50",
        NETFOX_MOVEMENT_ENABLED: "false",
        NETFOX_MOVEMENT_ALLOW_STATIC_FALLBACK: "true",
        SERVER_INSTANCE_ID: "pixelmania-a",
        SERVER_INSTANCE_WS_URL: "wss://api.pixelmaniagame.com/ws-a",
        PUBLIC_WS_URL: "wss://api.pixelmaniagame.com/ws-a",
        PORT: "18091",
      },
    },
    {
      name: "pixelmania-b",
      script: "server.js",
      cwd: __dirname,
      exec_mode: "fork",
      instances: 1,
      watch: false,
      time: true,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",
        REDIS_ENABLED: "true",
        POSTGRES_ENABLED: "true",
        POSTGRES_AUTHORITATIVE: "true",
        ALLOW_AUTHORITATIVE_JSON_FALLBACK: "false",
        REQUIRE_POSTGRES_AUTHORITATIVE_FOR_GAMEPLAY: "true",
        WORLD_ROUTE_ENFORCEMENT_ENABLED: "true",
        REDIS_REQUIRED_FOR_ROUTE_ENFORCEMENT: "true",
        WORLD_ROUTE_TTL_MS: "45000",
        WORLD_ADMISSION_TTL_MS: "45000",
        MAX_PLAYERS_PER_WORLD: "50",
        NETFOX_MOVEMENT_ENABLED: "false",
        NETFOX_MOVEMENT_ALLOW_STATIC_FALLBACK: "true",
        SERVER_INSTANCE_ID: "pixelmania-b",
        SERVER_INSTANCE_WS_URL: "wss://api.pixelmaniagame.com/ws-b",
        PUBLIC_WS_URL: "wss://api.pixelmaniagame.com/ws-b",
        PORT: "18092",
      },
    },
  ],
};
